site_name: Aimee's Nook✨✨✨
site_url: https://www.ANook.cc/
site_author: Kitte
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
      primary: indigo
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: teal     
      accent: purple
    

  # logo: assets/favicon.png

plugins:
  - search
  - blog

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AimeeAngelia
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Aimee7234482241
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/AimeeAngelia" target="_blank" rel="noopener">Aimee Angelia</a>

nav:
  - Home: 
    - index.html
    - index.old.html
  - Commend: 
    - Commend/index.md
    - Commend/man.md
    - Commend/zip.md
    - Commend/up&down.md
    - Commend/env.md
    - Commend/SoftwareInstallation.md
    - Commend/ShortcutKey.md
    - Commend/hostProcess.md
    - Commend/process.md
    - Commend/port.md
    - Commend/net.md
    - Commend/PermissionControl.md
    - Commend/group.md
    - Commend/root.md
    - Commend/tail.md
    - Commend/RedirectionCharacter.md
    - Commend/PipeCharacter.md
    - Commend/wc.md
    - Commend/grep.md
    - Commend/echo``.md
    - Commend/echo.md
    - Commend/find.md
    - Commend/which.md
    - Commend/rm.md
    - Commend/mv.md
    - Commend/cp.md
    - Commend/more.md
    - Commend/cat.md
    - Commend/touch.md
    - Commend/mkdir.md
    - Commend/pwd.md
    - Commend/cd.md
    - Commend/ls.md
  - History:
    - History/index.md
    - History/sudo.md
    - History/vim.md
  - Software:
    - Software/index.md
    - Software/vim.md
  - Link:
    - index.md