site_name: Aimee's Nook✨✨✨
site_url: https://www.ANook.cc/
site_author: Kitte
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: zh-TW
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode
      primary: teal        accent: purple
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme:
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
      primary: indigo
      accent: green
  # logo: assets/favicon.png

plugins:
  - search
  - blog

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AimeeAngelia
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Aimee7234482241
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/AimeeAngelia" target="_blank" rel="noopener">Aimee Angelia</a>

nav:
  # - Home: Note/stir.md
  - Home: index.md
  # - About: about.md
  - Commend: 
    - Commend/index.md
    - Commend/ls.md
    - Commend/cd.md
    - Commend/pwd.md
    - Commend/mkdir.md
    - Commend/touch.md
    - Commend/cat.md
    - Commend/more.md
    - Commend/cp.md
    - Commend/mv.md
    - Commend/rm.md
    - Commend/which.md
    - Commend/find.md
    - Commend/echo.md
    - Commend/echo``.md
    - Commend/grep.md
    - Commend/wc.md
    - Commend/PipeCharacter.md
    - Commend/RedirectionCharacter.md
    - Commend/tail.md
  - Software:
    - Software/index.md
    - Software/vim.md
  - time:
    - 16.md
    - 26.md
    - 36.md
    - 46.md
    - 56.md
    - 66.md
  # - Ubuntu-Exploring: 
    # - Ubuntu-Exploring/clash.md
    # - Ubuntu-Exploring/index.md
  # - Note:
    # - Note/stir.md
    # - Note/fonts.md
